[REQUESTS]
TOO_MANY_REQUESTS = "请求太频繁~~"

[STATE]
SUCCESS = "成功"
ERROR = "错误"
FAIL = "系统异常"

[AUTHOIRZE]
EMPTY_ACCOUNT="账号为空"
EMPTY_PASSWORD="空密码"
ERROR_PASSWORD="错误密码"
ERROR_SING_PASSWORD="密码校验失败"
NOT_EXISTS_ACCOUNT="账号不不存在"
EXISTS_ACCOUNT="账号不已存在"

[CAPTCHA]
ERROR_GENERATE_CODE="验证码生产失败"
ERROR_STORE_CODE="验证码存储失败"
ERROR_CHECK="验证码填写错误"
