# release or debug or test
NAME: "qiyang"
RUN_MODE: "debug"
RUN_USER: "git"
DEBUG: true
DOMAIN: "127.0.0.1"
ADDR: "localhost:3000"
VERSION: "v1.0.0"
WRITE_TIMEOUT: 120
READ_TIMEOUT: 120
MAX_REQUESTS: 10
MAX_REQUEST_TIME: 60
TIME_ZONES: "Asia/Shanghai"

SERVICE:

DATABASE:
  DRIVER: "pgx"

CACHE:
  DRIVER: "cache"
  EXPIRES: 60

CONNS:
  PGX:
    DRIVER: pgx
    MAX_OPEN_CONN: 100
    MAX_IDLE_CONN: 50
    DATABASE: "qiyang"
    READ:
      HOST: "localhost"
      PORT: 5432
      USERNAME: "qiyang"
      PASSWORD: "qiyang"
    WRITE:
      HOST: "localhost"
      PORT: 5432
      USERNAME: "qiyang"
      PASSWORD: "qiyang"
  Cache:
    DRIVER: "redis"
    ADDR: "localhost:6379"
    PASSWORD: ""
    DATABASE: 0
    MAX_OPEN_CONN: 100
    MAX_IDLE_CONN: 50
    MAX_ACTIVE: 30
    READ_TIMEOUT: 10
    DIAL_TIMEOUT: 10
    WRITE_TIMEOUT: 10
    POOL_SIZE: 10
    POOL_TIMEOUT: 30
  CAPTCHA:
    DRIVER: "redis"
    ADDR: "localhost:6379"
    PASSWORD: ""
    DATABASE: 0
    MAX_OPEN_CONN: 100
    MAX_IDLE_CONN: 50
    MAX_ACTIVE: 30
    READ_TIMEOUT: 10
    DIAL_TIMEOUT: 10
    WRITE_TIMEOUT: 10
    POOL_SIZE: 10
    POOL_TIMEOUT: 30

CAPTCHA:
  ENABLE: false
  TYPE: "image"
  EXPIRES: 60
  STORE: "captcha"
  DRIVERS:
    IMAGE:
      HEIGHT: 70
      WIDTH: 130
      LEN: 4
      DOT_COUNT: 100
      MAX_SKEW: 0.8
    TextPoint:
      Fonts:
        - "a"
        - "b"
      Chars: ["你","好","呀","这","是","点","击","验","证","码","哟"]
      Size:
        width: 100
        height: 100



CRON:
  #enable running cron tasks periodically.
  ENABLED: true
  #run cron tasks when gogs starts.
  RUN_AT_START: false
SECURITY:
  #Password Hash algorithm, either "argon2", "pbkdf2", "scrypt" or "bcrypt"
  KEY: "!#@fdewrewr&*("
  PASSWD_HASH_ALGO: "pbkdf2"
  PASSWORD_CHECK_PWN: false
  PASSWORD_COMPLEXITY: "off"
LOG:
  #debug info warn error dpanic panic fatal
  LEVEL: "debug"
  FILE_NAME: "record.log"
  # default 120 m
  MAX_SIZE: 1
  # save days
  MAX_AGE: 7
  MAX_BACKUPS: 30
  COMPRESS: true