# release or debug or test
run_mode = "debug"
run_user = "git"
debug = true
domain = "127.0.0.1"
addr = 'localhost:3000'
version = 'v1.0.0'
write_timeout = 120
read_timeout = 120
max_requests = 10
max_request_time = 60
secret_key = "!#@fdewrewr&*("

[database]
driver = "pgx"

[cache]
driver = "cache-redis"
expires = 60

[cron]
#enable running cron tasks periodically.
enabled = true
#run cron tasks when gogs starts.
run_at_start = false

[[conns]]
name = "pgx"
driver = "pgx"
read = { host = "localhost", port = 5432, username = "qiyang", password = "qiyang", database = "qiyang", max_open_conns = 100, max_idle_conns = 50 }
write = { host = "localhost", port = 5432, username = "qiyang", password = "qiyang", database = "qiyang", max_open_conns = 100, max_idle_conns = 50 }
[[conns]]
name = "cache-redis"
driver = "redis"
addr = "localhost:6379"
password = ""
database = 0
max_open_conns = 100
max_idle_conns = 50
max_active = 30
read_timeout=10
dial_timeout=10
write_timeout=10
pool_size = 10
pool_timeout = 30

[log]
#debug info warn error dpanic panic fatal
level = "debug"
file_name = "record.log"
# default 120 m
max_size = 1
# save days
max_age = 7
max_backups = 30
compress = true

[token]
privatekey = "/resources/certificate/token/rsaprivate.key"
publickey = "/resources/certificate/token/rsapublic.key"
signing = "signing"
expires_time = 60