# release or debug or test
name: "qiyang"
run_mode: "debug"
run_user: "git"
debug: true
domain: "127.0.0.1"
addr: "localhost:3000"
version: "v1.0.0"
write_timeout: 120
read_timeout: 120
max_requests: 10
max_request_time: 60
time_zones: "Asia/Shanghai"

database:
  driver: "pgx"

cache:
  driver: "cache"
  expires: 60
session:
  key: "QiYang"
  store: "session"
conns:
  pgx:
    driver: pgx
    max_open_conn: 100
    max_idle_conn: 50
    database: "qi_yang"
    read:
      host: "localhost"
      port:
      username: "qi_yang"
      password: "qi_yang"
    write:
      host: "localhost"
      port: 5432
      username: "qi_yang"
      password: "qi_yang"
  cache:
    driver: "redis"
    addr: "localhost:6379"
    password: ""
    database: 0
    max_open_conn: 100
    max_idle_conn: 50
    max_active: 30
    read_timeout: 10
    dial_timeout: 10
    write_timeout: 10
    pool_size: 10
    pool_timeout: 30
  captcha:
    driver: "redis"
    addr: "localhost:6379"
    password: ""
    database: 0
    max_open_conn: 100
    max_idle_conn: 50
    max_active: 30
    read_timeout: 10
    dial_timeout: 10
    write_timeout: 10
    pool_size: 10
    pool_timeout: 30
  session:
    driver: "redis"
    addr: "localhost:6379"
    net: "tcp"
    password: ""
    database: 0

captcha:
  enable: false
  type: "image"
  expires: 60
  store: "captcha"
  drivers:
    image:
      height: 70
      width: 130
      len: 4
      dot_count: 100
      max_skew: 0.8
    textpoint:
      fonts:
        - "a"
        - "b"
      chars: ["你","好","呀","这","是","点","击","验","证","码","哟"]
      size:
        width: 100
        height: 100



cron:
  #enable running cron tasks periodically.
  enabled: true
  #run cron tasks when gogs starts.
  run_at_start: false
security:
  #password hash algorithm, either "argon2", "pbkdf2", "scrypt" or "bcrypt"
  key: "!#@fdewrewr&*("
  passwd_hash_algo: "pbkdf2"
  password_check_pwn: false
  password_complexity: "off"
log:
  #debug info warn error dpanic panic fatal
  level: "debug"
  file_name: "record.log"
  # default 120 m
  max_size: 1
  # save days
  max_age: 7
  max_backups: 30
  compress: true