// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"service-api/src/models/ent/memberrelatedrole"
	"service-api/src/models/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// MemberRelatedRoleQuery is the builder for querying MemberRelatedRole entities.
type MemberRelatedRoleQuery struct {
	config
	ctx        *QueryContext
	order      []memberrelatedrole.OrderOption
	inters     []Interceptor
	predicates []predicate.MemberRelatedRole
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MemberRelatedRoleQuery builder.
func (mrrq *MemberRelatedRoleQuery) Where(ps ...predicate.MemberRelatedRole) *MemberRelatedRoleQuery {
	mrrq.predicates = append(mrrq.predicates, ps...)
	return mrrq
}

// Limit the number of records to be returned by this query.
func (mrrq *MemberRelatedRoleQuery) Limit(limit int) *MemberRelatedRoleQuery {
	mrrq.ctx.Limit = &limit
	return mrrq
}

// Offset to start from.
func (mrrq *MemberRelatedRoleQuery) Offset(offset int) *MemberRelatedRoleQuery {
	mrrq.ctx.Offset = &offset
	return mrrq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (mrrq *MemberRelatedRoleQuery) Unique(unique bool) *MemberRelatedRoleQuery {
	mrrq.ctx.Unique = &unique
	return mrrq
}

// Order specifies how the records should be ordered.
func (mrrq *MemberRelatedRoleQuery) Order(o ...memberrelatedrole.OrderOption) *MemberRelatedRoleQuery {
	mrrq.order = append(mrrq.order, o...)
	return mrrq
}

// First returns the first MemberRelatedRole entity from the query.
// Returns a *NotFoundError when no MemberRelatedRole was found.
func (mrrq *MemberRelatedRoleQuery) First(ctx context.Context) (*MemberRelatedRole, error) {
	nodes, err := mrrq.Limit(1).All(setContextOp(ctx, mrrq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{memberrelatedrole.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (mrrq *MemberRelatedRoleQuery) FirstX(ctx context.Context) *MemberRelatedRole {
	node, err := mrrq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MemberRelatedRole ID from the query.
// Returns a *NotFoundError when no MemberRelatedRole ID was found.
func (mrrq *MemberRelatedRoleQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = mrrq.Limit(1).IDs(setContextOp(ctx, mrrq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{memberrelatedrole.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (mrrq *MemberRelatedRoleQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := mrrq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MemberRelatedRole entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MemberRelatedRole entity is found.
// Returns a *NotFoundError when no MemberRelatedRole entities are found.
func (mrrq *MemberRelatedRoleQuery) Only(ctx context.Context) (*MemberRelatedRole, error) {
	nodes, err := mrrq.Limit(2).All(setContextOp(ctx, mrrq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{memberrelatedrole.Label}
	default:
		return nil, &NotSingularError{memberrelatedrole.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (mrrq *MemberRelatedRoleQuery) OnlyX(ctx context.Context) *MemberRelatedRole {
	node, err := mrrq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MemberRelatedRole ID in the query.
// Returns a *NotSingularError when more than one MemberRelatedRole ID is found.
// Returns a *NotFoundError when no entities are found.
func (mrrq *MemberRelatedRoleQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = mrrq.Limit(2).IDs(setContextOp(ctx, mrrq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{memberrelatedrole.Label}
	default:
		err = &NotSingularError{memberrelatedrole.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (mrrq *MemberRelatedRoleQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := mrrq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MemberRelatedRoles.
func (mrrq *MemberRelatedRoleQuery) All(ctx context.Context) ([]*MemberRelatedRole, error) {
	ctx = setContextOp(ctx, mrrq.ctx, "All")
	if err := mrrq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*MemberRelatedRole, *MemberRelatedRoleQuery]()
	return withInterceptors[[]*MemberRelatedRole](ctx, mrrq, qr, mrrq.inters)
}

// AllX is like All, but panics if an error occurs.
func (mrrq *MemberRelatedRoleQuery) AllX(ctx context.Context) []*MemberRelatedRole {
	nodes, err := mrrq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MemberRelatedRole IDs.
func (mrrq *MemberRelatedRoleQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if mrrq.ctx.Unique == nil && mrrq.path != nil {
		mrrq.Unique(true)
	}
	ctx = setContextOp(ctx, mrrq.ctx, "IDs")
	if err = mrrq.Select(memberrelatedrole.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (mrrq *MemberRelatedRoleQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := mrrq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (mrrq *MemberRelatedRoleQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, mrrq.ctx, "Count")
	if err := mrrq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, mrrq, querierCount[*MemberRelatedRoleQuery](), mrrq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (mrrq *MemberRelatedRoleQuery) CountX(ctx context.Context) int {
	count, err := mrrq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (mrrq *MemberRelatedRoleQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, mrrq.ctx, "Exist")
	switch _, err := mrrq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (mrrq *MemberRelatedRoleQuery) ExistX(ctx context.Context) bool {
	exist, err := mrrq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MemberRelatedRoleQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (mrrq *MemberRelatedRoleQuery) Clone() *MemberRelatedRoleQuery {
	if mrrq == nil {
		return nil
	}
	return &MemberRelatedRoleQuery{
		config:     mrrq.config,
		ctx:        mrrq.ctx.Clone(),
		order:      append([]memberrelatedrole.OrderOption{}, mrrq.order...),
		inters:     append([]Interceptor{}, mrrq.inters...),
		predicates: append([]predicate.MemberRelatedRole{}, mrrq.predicates...),
		// clone intermediate query.
		sql:  mrrq.sql.Clone(),
		path: mrrq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MemberRelatedRole.Query().
//		GroupBy(memberrelatedrole.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (mrrq *MemberRelatedRoleQuery) GroupBy(field string, fields ...string) *MemberRelatedRoleGroupBy {
	mrrq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &MemberRelatedRoleGroupBy{build: mrrq}
	grbuild.flds = &mrrq.ctx.Fields
	grbuild.label = memberrelatedrole.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.MemberRelatedRole.Query().
//		Select(memberrelatedrole.FieldCreateTime).
//		Scan(ctx, &v)
func (mrrq *MemberRelatedRoleQuery) Select(fields ...string) *MemberRelatedRoleSelect {
	mrrq.ctx.Fields = append(mrrq.ctx.Fields, fields...)
	sbuild := &MemberRelatedRoleSelect{MemberRelatedRoleQuery: mrrq}
	sbuild.label = memberrelatedrole.Label
	sbuild.flds, sbuild.scan = &mrrq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a MemberRelatedRoleSelect configured with the given aggregations.
func (mrrq *MemberRelatedRoleQuery) Aggregate(fns ...AggregateFunc) *MemberRelatedRoleSelect {
	return mrrq.Select().Aggregate(fns...)
}

func (mrrq *MemberRelatedRoleQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range mrrq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, mrrq); err != nil {
				return err
			}
		}
	}
	for _, f := range mrrq.ctx.Fields {
		if !memberrelatedrole.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if mrrq.path != nil {
		prev, err := mrrq.path(ctx)
		if err != nil {
			return err
		}
		mrrq.sql = prev
	}
	return nil
}

func (mrrq *MemberRelatedRoleQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*MemberRelatedRole, error) {
	var (
		nodes = []*MemberRelatedRole{}
		_spec = mrrq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*MemberRelatedRole).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &MemberRelatedRole{config: mrrq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, mrrq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (mrrq *MemberRelatedRoleQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := mrrq.querySpec()
	_spec.Node.Columns = mrrq.ctx.Fields
	if len(mrrq.ctx.Fields) > 0 {
		_spec.Unique = mrrq.ctx.Unique != nil && *mrrq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, mrrq.driver, _spec)
}

func (mrrq *MemberRelatedRoleQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(memberrelatedrole.Table, memberrelatedrole.Columns, sqlgraph.NewFieldSpec(memberrelatedrole.FieldID, field.TypeUUID))
	_spec.From = mrrq.sql
	if unique := mrrq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if mrrq.path != nil {
		_spec.Unique = true
	}
	if fields := mrrq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, memberrelatedrole.FieldID)
		for i := range fields {
			if fields[i] != memberrelatedrole.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := mrrq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := mrrq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := mrrq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := mrrq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (mrrq *MemberRelatedRoleQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(mrrq.driver.Dialect())
	t1 := builder.Table(memberrelatedrole.Table)
	columns := mrrq.ctx.Fields
	if len(columns) == 0 {
		columns = memberrelatedrole.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if mrrq.sql != nil {
		selector = mrrq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if mrrq.ctx.Unique != nil && *mrrq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range mrrq.predicates {
		p(selector)
	}
	for _, p := range mrrq.order {
		p(selector)
	}
	if offset := mrrq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := mrrq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MemberRelatedRoleGroupBy is the group-by builder for MemberRelatedRole entities.
type MemberRelatedRoleGroupBy struct {
	selector
	build *MemberRelatedRoleQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (mrrgb *MemberRelatedRoleGroupBy) Aggregate(fns ...AggregateFunc) *MemberRelatedRoleGroupBy {
	mrrgb.fns = append(mrrgb.fns, fns...)
	return mrrgb
}

// Scan applies the selector query and scans the result into the given value.
func (mrrgb *MemberRelatedRoleGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mrrgb.build.ctx, "GroupBy")
	if err := mrrgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MemberRelatedRoleQuery, *MemberRelatedRoleGroupBy](ctx, mrrgb.build, mrrgb, mrrgb.build.inters, v)
}

func (mrrgb *MemberRelatedRoleGroupBy) sqlScan(ctx context.Context, root *MemberRelatedRoleQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(mrrgb.fns))
	for _, fn := range mrrgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*mrrgb.flds)+len(mrrgb.fns))
		for _, f := range *mrrgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*mrrgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mrrgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// MemberRelatedRoleSelect is the builder for selecting fields of MemberRelatedRole entities.
type MemberRelatedRoleSelect struct {
	*MemberRelatedRoleQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (mrrs *MemberRelatedRoleSelect) Aggregate(fns ...AggregateFunc) *MemberRelatedRoleSelect {
	mrrs.fns = append(mrrs.fns, fns...)
	return mrrs
}

// Scan applies the selector query and scans the result into the given value.
func (mrrs *MemberRelatedRoleSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mrrs.ctx, "Select")
	if err := mrrs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MemberRelatedRoleQuery, *MemberRelatedRoleSelect](ctx, mrrs.MemberRelatedRoleQuery, mrrs, mrrs.inters, v)
}

func (mrrs *MemberRelatedRoleSelect) sqlScan(ctx context.Context, root *MemberRelatedRoleQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(mrrs.fns))
	for _, fn := range mrrs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*mrrs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mrrs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
