// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"service-api/src/models/ent/predicate"
	"service-api/src/models/ent/wakatimeeditor"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WakatimeEditorUpdate is the builder for updating WakatimeEditor entities.
type WakatimeEditorUpdate struct {
	config
	hooks    []Hook
	mutation *WakatimeEditorMutation
}

// Where appends a list predicates to the WakatimeEditorUpdate builder.
func (weu *WakatimeEditorUpdate) Where(ps ...predicate.WakatimeEditor) *WakatimeEditorUpdate {
	weu.mutation.Where(ps...)
	return weu
}

// Mutation returns the WakatimeEditorMutation object of the builder.
func (weu *WakatimeEditorUpdate) Mutation() *WakatimeEditorMutation {
	return weu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (weu *WakatimeEditorUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, weu.sqlSave, weu.mutation, weu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (weu *WakatimeEditorUpdate) SaveX(ctx context.Context) int {
	affected, err := weu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (weu *WakatimeEditorUpdate) Exec(ctx context.Context) error {
	_, err := weu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (weu *WakatimeEditorUpdate) ExecX(ctx context.Context) {
	if err := weu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (weu *WakatimeEditorUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(wakatimeeditor.Table, wakatimeeditor.Columns, sqlgraph.NewFieldSpec(wakatimeeditor.FieldID, field.TypeInt))
	if ps := weu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if n, err = sqlgraph.UpdateNodes(ctx, weu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{wakatimeeditor.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	weu.mutation.done = true
	return n, nil
}

// WakatimeEditorUpdateOne is the builder for updating a single WakatimeEditor entity.
type WakatimeEditorUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WakatimeEditorMutation
}

// Mutation returns the WakatimeEditorMutation object of the builder.
func (weuo *WakatimeEditorUpdateOne) Mutation() *WakatimeEditorMutation {
	return weuo.mutation
}

// Where appends a list predicates to the WakatimeEditorUpdate builder.
func (weuo *WakatimeEditorUpdateOne) Where(ps ...predicate.WakatimeEditor) *WakatimeEditorUpdateOne {
	weuo.mutation.Where(ps...)
	return weuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (weuo *WakatimeEditorUpdateOne) Select(field string, fields ...string) *WakatimeEditorUpdateOne {
	weuo.fields = append([]string{field}, fields...)
	return weuo
}

// Save executes the query and returns the updated WakatimeEditor entity.
func (weuo *WakatimeEditorUpdateOne) Save(ctx context.Context) (*WakatimeEditor, error) {
	return withHooks(ctx, weuo.sqlSave, weuo.mutation, weuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (weuo *WakatimeEditorUpdateOne) SaveX(ctx context.Context) *WakatimeEditor {
	node, err := weuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (weuo *WakatimeEditorUpdateOne) Exec(ctx context.Context) error {
	_, err := weuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (weuo *WakatimeEditorUpdateOne) ExecX(ctx context.Context) {
	if err := weuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (weuo *WakatimeEditorUpdateOne) sqlSave(ctx context.Context) (_node *WakatimeEditor, err error) {
	_spec := sqlgraph.NewUpdateSpec(wakatimeeditor.Table, wakatimeeditor.Columns, sqlgraph.NewFieldSpec(wakatimeeditor.FieldID, field.TypeInt))
	id, ok := weuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WakatimeEditor.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := weuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, wakatimeeditor.FieldID)
		for _, f := range fields {
			if !wakatimeeditor.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != wakatimeeditor.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := weuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_node = &WakatimeEditor{config: weuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, weuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{wakatimeeditor.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	weuo.mutation.done = true
	return _node, nil
}
