// Code generated by ent, DO NOT EDIT.

package memberauthorizelog

import (
	"time"

	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the memberauthorizelog type in the database.
	Label = "member_authorize_log"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldMemberID holds the string denoting the member_id field in the database.
	FieldMemberID = "member_id"
	// FieldChannel holds the string denoting the channel field in the database.
	FieldChannel = "channel"
	// FieldDevice holds the string denoting the device field in the database.
	FieldDevice = "device"
	// FieldDeviceDetail holds the string denoting the device_detail field in the database.
	FieldDeviceDetail = "device_detail"
	// FieldIpv4 holds the string denoting the ipv4 field in the database.
	FieldIpv4 = "ipv4"
	// FieldIpv6 holds the string denoting the ipv6 field in the database.
	FieldIpv6 = "ipv6"
	// FieldSnapshot holds the string denoting the snapshot field in the database.
	FieldSnapshot = "snapshot"
	// Table holds the table name of the memberauthorizelog in the database.
	Table = "member_authorize_logs"
)

// Columns holds all SQL columns for memberauthorizelog fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldMemberID,
	FieldChannel,
	FieldDevice,
	FieldDeviceDetail,
	FieldIpv4,
	FieldIpv6,
	FieldSnapshot,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// DefaultMemberID holds the default value on creation for the "member_id" field.
	DefaultMemberID func() uuid.UUID
	// DeviceValidator is a validator for the "device" field. It is called by the builders before save.
	DeviceValidator func(string) error
	// DeviceDetailValidator is a validator for the "device_detail" field. It is called by the builders before save.
	DeviceDetailValidator func(string) error
	// Ipv4Validator is a validator for the "ipv4" field. It is called by the builders before save.
	Ipv4Validator func(string) error
	// Ipv6Validator is a validator for the "ipv6" field. It is called by the builders before save.
	Ipv6Validator func(string) error
	// SnapshotValidator is a validator for the "snapshot" field. It is called by the builders before save.
	SnapshotValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
