// Code generated by ent, DO NOT EDIT.

package models

import (
	"ent/models/wakatimeheartbeat"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// WakatimeHeartBeat is the model entity for the WakatimeHeartBeat schema.
type WakatimeHeartBeat struct {
	config
	// ID of the ent.
	ID           int64 `json:"id,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*WakatimeHeartBeat) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case wakatimeheartbeat.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the WakatimeHeartBeat fields.
func (whb *WakatimeHeartBeat) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case wakatimeheartbeat.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			whb.ID = int64(value.Int64)
		default:
			whb.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the WakatimeHeartBeat.
// This includes values selected through modifiers, order, etc.
func (whb *WakatimeHeartBeat) Value(name string) (ent.Value, error) {
	return whb.selectValues.Get(name)
}

// Update returns a builder for updating this WakatimeHeartBeat.
// Note that you need to call WakatimeHeartBeat.Unwrap() before calling this method if this WakatimeHeartBeat
// was returned from a transaction, and the transaction was committed or rolled back.
func (whb *WakatimeHeartBeat) Update() *WakatimeHeartBeatUpdateOne {
	return NewWakatimeHeartBeatClient(whb.config).UpdateOne(whb)
}

// Unwrap unwraps the WakatimeHeartBeat entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (whb *WakatimeHeartBeat) Unwrap() *WakatimeHeartBeat {
	_tx, ok := whb.config.driver.(*txDriver)
	if !ok {
		panic("models: WakatimeHeartBeat is not a transactional entity")
	}
	whb.config.driver = _tx.drv
	return whb
}

// String implements the fmt.Stringer.
func (whb *WakatimeHeartBeat) String() string {
	var builder strings.Builder
	builder.WriteString("WakatimeHeartBeat(")
	builder.WriteString(fmt.Sprintf("id=%v", whb.ID))
	builder.WriteByte(')')
	return builder.String()
}

// WakatimeHeartBeats is a parsable slice of WakatimeHeartBeat.
type WakatimeHeartBeats []*WakatimeHeartBeat
