// Code generated by ent, DO NOT EDIT.

package models

import (
	"context"
	"ent/models/predicate"
	"ent/models/wakatimelanguage"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WakatimeLanguageUpdate is the builder for updating WakatimeLanguage entities.
type WakatimeLanguageUpdate struct {
	config
	hooks    []Hook
	mutation *WakatimeLanguageMutation
}

// Where appends a list predicates to the WakatimeLanguageUpdate builder.
func (wlu *WakatimeLanguageUpdate) Where(ps ...predicate.WakatimeLanguage) *WakatimeLanguageUpdate {
	wlu.mutation.Where(ps...)
	return wlu
}

// Mutation returns the WakatimeLanguageMutation object of the builder.
func (wlu *WakatimeLanguageUpdate) Mutation() *WakatimeLanguageMutation {
	return wlu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (wlu *WakatimeLanguageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, wlu.sqlSave, wlu.mutation, wlu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (wlu *WakatimeLanguageUpdate) SaveX(ctx context.Context) int {
	affected, err := wlu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (wlu *WakatimeLanguageUpdate) Exec(ctx context.Context) error {
	_, err := wlu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wlu *WakatimeLanguageUpdate) ExecX(ctx context.Context) {
	if err := wlu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (wlu *WakatimeLanguageUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(wakatimelanguage.Table, wakatimelanguage.Columns, sqlgraph.NewFieldSpec(wakatimelanguage.FieldID, field.TypeInt64))
	if ps := wlu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if n, err = sqlgraph.UpdateNodes(ctx, wlu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{wakatimelanguage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	wlu.mutation.done = true
	return n, nil
}

// WakatimeLanguageUpdateOne is the builder for updating a single WakatimeLanguage entity.
type WakatimeLanguageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WakatimeLanguageMutation
}

// Mutation returns the WakatimeLanguageMutation object of the builder.
func (wluo *WakatimeLanguageUpdateOne) Mutation() *WakatimeLanguageMutation {
	return wluo.mutation
}

// Where appends a list predicates to the WakatimeLanguageUpdate builder.
func (wluo *WakatimeLanguageUpdateOne) Where(ps ...predicate.WakatimeLanguage) *WakatimeLanguageUpdateOne {
	wluo.mutation.Where(ps...)
	return wluo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (wluo *WakatimeLanguageUpdateOne) Select(field string, fields ...string) *WakatimeLanguageUpdateOne {
	wluo.fields = append([]string{field}, fields...)
	return wluo
}

// Save executes the query and returns the updated WakatimeLanguage entity.
func (wluo *WakatimeLanguageUpdateOne) Save(ctx context.Context) (*WakatimeLanguage, error) {
	return withHooks(ctx, wluo.sqlSave, wluo.mutation, wluo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (wluo *WakatimeLanguageUpdateOne) SaveX(ctx context.Context) *WakatimeLanguage {
	node, err := wluo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (wluo *WakatimeLanguageUpdateOne) Exec(ctx context.Context) error {
	_, err := wluo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wluo *WakatimeLanguageUpdateOne) ExecX(ctx context.Context) {
	if err := wluo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (wluo *WakatimeLanguageUpdateOne) sqlSave(ctx context.Context) (_node *WakatimeLanguage, err error) {
	_spec := sqlgraph.NewUpdateSpec(wakatimelanguage.Table, wakatimelanguage.Columns, sqlgraph.NewFieldSpec(wakatimelanguage.FieldID, field.TypeInt64))
	id, ok := wluo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`models: missing "WakatimeLanguage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := wluo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, wakatimelanguage.FieldID)
		for _, f := range fields {
			if !wakatimelanguage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("models: invalid field %q for query", f)}
			}
			if f != wakatimelanguage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := wluo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_node = &WakatimeLanguage{config: wluo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, wluo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{wakatimelanguage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	wluo.mutation.done = true
	return _node, nil
}
