[server]
host = '0.0.0.0'
port = 3000
env = "debug"

[database]

[database.pg]
type = "pgx"
host = "localhost"
port = 5432
username = "qi_yang"
password = "qi_yang"
database = "qi_yang"

[database.pg.config]
maxOpenConns = 100
maxIdleConns = 50

[database.redis]
host = "redis"
password = ""
maxIdleConns = 50
maxActive = 30
idleTimeout = 200

[cache]
drive = "redis"
expires = 60

[cache.redis]
database = 0

[token]
privateKey = "a"
publicKey = "a"
signing = "signing"
expiresTime = 60
