[server]
host = '0.0.0.0'
port = 3000
env = "debug"

[database]
type = "pgx"

[database.pgx]
host = "localhost"
port = 5432
username = "qi_yang"
password = "qi_yang"
database = "qi_yang"

[database.pgx.config]
maxOpenConns = 100
maxIdleConns = 50

[database.redis]
host = "127.0.0.1"
port = 6379
password = ""
maxIdleConns = 50
maxActive = 30
idleTimeout = 200

[cache]
driver = "redis"
expires = 60

[cache.redis]
database = 0

[token]
privateKey = "/resources/certificate/token/RSAPrivate.key"
publicKey = "/resources/certificate/token/RSAPublic.key"
signing = "signing"
expiresTime = 60
