CAPTCHA_CREATION_FAILED = "Error generating captcha"
CAPTCHA_GENERATION_FAILED = "Captcha generation failed"
CAPTCHA_ID_EMPTY = "Captcha id missing"
CAPTCHA_INPUT_EMPTY = "Captcha value not provided"
CAPTCHA_NOT_ACTIVATED = "Captcha is not activated."
CAPTCHA_STORAGE_FAILURE = "Failed to store generated captcha"
CAPTCHA_TOKEN_MISSING = "Captcha token is missing."
CAPTCHA_VALIDATION_FAILED = "Captcha validation failed"
EMAIL_IN_USE = "This email address is already in use."
EMAIL_NOT_FOUND = "The provided email address could not be found."
REQUESTS_TOO_MANY = "Too many requests"
"STATE.Fail" = "Fail !"
STATE_ERROR = "Error !"
STATE_SUCCESS = "Success"
USER_EMAIL_EMPTY = "Please provide an email address."
USER_EMAIL_FORMAT_INVALID = "The email address format is invalid."
USER_PASSWORD_CHECK_FAILED = "The password does not meet the requirements."
USER_PASSWORD_EMPTY = "Please enter a password."
WELCOME = "Welcome !"
