[server]
debug = true
domain = "localhost"
addr = '0.0.0.0'
port = 3000
runMode = "debug"

[serve.config]
writeTimeout = 120
readTimeout = 120

[database]
type = "pgx"

[database.read]
host = "localhost"
port = 5432
username = "qi_yang"
password = "qi_yang"
database = "qi_yang"

[database.write]
host = "localhost"
port = 5432
username = "qi_yang"
password = "qi_yang"
database = "qi_yang"

[database.config]
maxOpenConns = 100
maxIdleConns = 50

[database.cache]
host = "localhost"
port = 6379
type = "redis"
password = "secret_redis"
maxIdleConns = 50
maxActive = 30
idleTimeout = 200

[cache]
driver = "redis"
expires = 60

[cache.redis]
database = 0

[log]
# -1~5
level = 5
fileName = "log"
# default 120 M
maxSize = 120
# save days
maxAge = 7
maxBackups = 30
Compress = true





[token]
privateKey = "/resources/certificate/token/RSAPrivate.key"
publicKey = "/resources/certificate/token/RSAPublic.key"
signing = "signing"
expiresTime = 60
