basePath: /api
definitions:
  response.Response:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
      request_id:
        type: string
      state:
        $ref: '#/definitions/response.StateEnum'
      timestamp:
        type: string
    type: object
  response.StateEnum:
    enum:
    - success
    - error
    - warn
    - fail
    type: string
    x-enum-varnames:
    - Success
    - Error
    - Warn
    - Fail
  validator.CaptchaResponse:
    properties:
      captcha:
        type: string
      id:
        type: string
      token:
        type: string
    type: object
  validator.CaptchaVerifyRequest:
    properties:
      answer:
        type: string
      id:
        type: string
      token:
        type: string
      type:
        type: string
    required:
    - answer
    - id
    - token
    type: object
info:
  contact:
    email: notice@myadream.com
    name: QiYang
    url: https://github.com/QiYangApp/service-api
  description: QiYangApiService
  license:
    name: BSD 3-Clause "New" or "Revised" License
    url: https://github.com/QiYangApp/service-api/blob/main/LICENSE
  termsOfService: http://swagger.io/terms/
  title: QiYang
  version: "1.0"
paths:
  /captcha/{type}:
    get:
      consumes:
      - application/json
      description: 获取验证码
      parameters:
      - description: 验证码授权类型
        in: path
        name: type
        required: true
        type: string
      - description: token
        in: query
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 请求成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                Data:
                  $ref: '#/definitions/validator.CaptchaResponse'
              type: object
      summary: 获取验证码
    post:
      consumes:
      - application/json
      description: 校验验证码
      parameters:
      - description: 验证码授权类型
        in: path
        name: type
        required: true
        type: string
      - description: data
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/validator.CaptchaVerifyRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 请求成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                Data:
                  type: boolean
              type: object
      summary: 校验验证码
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
