// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// MembersColumns holds the columns for the "members" table.
	MembersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Comment: "UUID of the"},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "email", Type: field.TypeString, Size: 128},
		{Name: "avatar", Type: field.TypeString},
		{Name: "password_sing", Type: field.TypeString, Size: 120},
		{Name: "password", Type: field.TypeString, Size: 32},
		{Name: "mobile", Type: field.TypeString, Size: 32},
		{Name: "nickname", Type: field.TypeString, Size: 32},
		{Name: "state", Type: field.TypeString, Size: 32},
	}
	// MembersTable holds the schema information for the "members" table.
	MembersTable = &schema.Table{
		Name:       "members",
		Comment:    "member",
		Columns:    MembersColumns,
		PrimaryKey: []*schema.Column{MembersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "member_mobile",
				Unique:  true,
				Columns: []*schema.Column{MembersColumns[7]},
			},
			{
				Name:    "member_email",
				Unique:  true,
				Columns: []*schema.Column{MembersColumns[3]},
			},
		},
	}
	// MemberAuthorizeLogsColumns holds the columns for the "member_authorize_logs" table.
	MemberAuthorizeLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "member_id", Type: field.TypeUUID},
		{Name: "token", Type: field.TypeString, Size: 254},
		{Name: "channel", Type: field.TypeString, Size: 64},
		{Name: "device", Type: field.TypeString, Size: 64},
		{Name: "device_detail", Type: field.TypeString, Size: 64},
		{Name: "client_ip", Type: field.TypeString, Size: 32},
		{Name: "remote_ip", Type: field.TypeString, Size: 32},
		{Name: "snapshot", Type: field.TypeString, Size: 254},
	}
	// MemberAuthorizeLogsTable holds the schema information for the "member_authorize_logs" table.
	MemberAuthorizeLogsTable = &schema.Table{
		Name:       "member_authorize_logs",
		Columns:    MemberAuthorizeLogsColumns,
		PrimaryKey: []*schema.Column{MemberAuthorizeLogsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "memberauthorizelog_member_id_channel_device",
				Unique:  false,
				Columns: []*schema.Column{MemberAuthorizeLogsColumns[3], MemberAuthorizeLogsColumns[5], MemberAuthorizeLogsColumns[6]},
			},
		},
	}
	// MemberRelatedRolesColumns holds the columns for the "member_related_roles" table.
	MemberRelatedRolesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "member_id", Type: field.TypeUUID},
		{Name: "role_id", Type: field.TypeUUID},
	}
	// MemberRelatedRolesTable holds the schema information for the "member_related_roles" table.
	MemberRelatedRolesTable = &schema.Table{
		Name:       "member_related_roles",
		Columns:    MemberRelatedRolesColumns,
		PrimaryKey: []*schema.Column{MemberRelatedRolesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "memberrelatedrole_member_id_role_id",
				Unique:  true,
				Columns: []*schema.Column{MemberRelatedRolesColumns[3], MemberRelatedRolesColumns[4]},
			},
		},
	}
	// MemberRolesColumns holds the columns for the "member_roles" table.
	MemberRolesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "role_name", Type: field.TypeString, Size: 64},
		{Name: "state", Type: field.TypeString, Size: 32, Default: "ON"},
	}
	// MemberRolesTable holds the schema information for the "member_roles" table.
	MemberRolesTable = &schema.Table{
		Name:       "member_roles",
		Columns:    MemberRolesColumns,
		PrimaryKey: []*schema.Column{MemberRolesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "memberrole_state_role_name",
				Unique:  true,
				Columns: []*schema.Column{MemberRolesColumns[4], MemberRolesColumns[3]},
			},
		},
	}
	// MemberRoleRelatedPermissionsColumns holds the columns for the "member_role_related_permissions" table.
	MemberRoleRelatedPermissionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "role_id", Type: field.TypeUUID},
		{Name: "permission_group_id", Type: field.TypeUUID},
	}
	// MemberRoleRelatedPermissionsTable holds the schema information for the "member_role_related_permissions" table.
	MemberRoleRelatedPermissionsTable = &schema.Table{
		Name:       "member_role_related_permissions",
		Columns:    MemberRoleRelatedPermissionsColumns,
		PrimaryKey: []*schema.Column{MemberRoleRelatedPermissionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "memberrolerelatedpermission_role_id_permission_group_id",
				Unique:  true,
				Columns: []*schema.Column{MemberRoleRelatedPermissionsColumns[3], MemberRoleRelatedPermissionsColumns[4]},
			},
		},
	}
	// PermissionGroupsColumns holds the columns for the "permission_groups" table.
	PermissionGroupsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "permission_name", Type: field.TypeString, Size: 32, Default: ""},
		{Name: "ioc", Type: field.TypeString, Size: 254, Default: ""},
		{Name: "sort", Type: field.TypeInt32, Default: 0},
		{Name: "left", Type: field.TypeInt32, Default: 0},
		{Name: "right", Type: field.TypeInt32, Default: 0},
		{Name: "state", Type: field.TypeString, Default: "ON"},
	}
	// PermissionGroupsTable holds the schema information for the "permission_groups" table.
	PermissionGroupsTable = &schema.Table{
		Name:       "permission_groups",
		Columns:    PermissionGroupsColumns,
		PrimaryKey: []*schema.Column{PermissionGroupsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "permissiongroup_left_right",
				Unique:  false,
				Columns: []*schema.Column{PermissionGroupsColumns[6], PermissionGroupsColumns[7]},
			},
			{
				Name:    "permissiongroup_state_sort_permission_name",
				Unique:  false,
				Columns: []*schema.Column{PermissionGroupsColumns[8], PermissionGroupsColumns[5], PermissionGroupsColumns[3]},
			},
		},
	}
	// PermissionRelatedRoutersColumns holds the columns for the "permission_related_routers" table.
	PermissionRelatedRoutersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "router_id", Type: field.TypeUUID},
		{Name: "permission_group_id", Type: field.TypeUUID},
	}
	// PermissionRelatedRoutersTable holds the schema information for the "permission_related_routers" table.
	PermissionRelatedRoutersTable = &schema.Table{
		Name:       "permission_related_routers",
		Columns:    PermissionRelatedRoutersColumns,
		PrimaryKey: []*schema.Column{PermissionRelatedRoutersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "permissionrelatedrouter_permission_group_id_router_id",
				Unique:  false,
				Columns: []*schema.Column{PermissionRelatedRoutersColumns[4], PermissionRelatedRoutersColumns[3]},
			},
		},
	}
	// RoutersColumns holds the columns for the "routers" table.
	RoutersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "route_name", Type: field.TypeString, Size: 32, Default: ""},
		{Name: "route", Type: field.TypeString, Size: 254, Default: ""},
		{Name: "description", Type: field.TypeString, Size: 254, Default: ""},
		{Name: "state", Type: field.TypeString, Size: 32, Default: "ON"},
	}
	// RoutersTable holds the schema information for the "routers" table.
	RoutersTable = &schema.Table{
		Name:       "routers",
		Columns:    RoutersColumns,
		PrimaryKey: []*schema.Column{RoutersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "router_state_route_name",
				Unique:  false,
				Columns: []*schema.Column{RoutersColumns[6], RoutersColumns[3]},
			},
			{
				Name:    "router_state_route",
				Unique:  false,
				Columns: []*schema.Column{RoutersColumns[6], RoutersColumns[4]},
			},
		},
	}
	// SourceDataColumns holds the columns for the "source_data" table.
	SourceDataColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "member_id", Type: field.TypeUUID},
		{Name: "type", Type: field.TypeString, Size: 32, Default: ""},
		{Name: "sub_type", Type: field.TypeString, Size: 32, Default: ""},
		{Name: "info", Type: field.TypeString, Default: ""},
		{Name: "snapshot", Type: field.TypeString, Size: 2147483647, Default: ""},
	}
	// SourceDataTable holds the schema information for the "source_data" table.
	SourceDataTable = &schema.Table{
		Name:       "source_data",
		Columns:    SourceDataColumns,
		PrimaryKey: []*schema.Column{SourceDataColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "sourcedata_member_id",
				Unique:  false,
				Columns: []*schema.Column{SourceDataColumns[3]},
			},
			{
				Name:    "sourcedata_type_sub_type",
				Unique:  false,
				Columns: []*schema.Column{SourceDataColumns[4], SourceDataColumns[5]},
			},
		},
	}
	// WakatimesColumns holds the columns for the "wakatimes" table.
	WakatimesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "member_id", Type: field.TypeUUID},
		{Name: "key", Type: field.TypeString},
		{Name: "api", Type: field.TypeString},
		{Name: "state", Type: field.TypeString},
	}
	// WakatimesTable holds the schema information for the "wakatimes" table.
	WakatimesTable = &schema.Table{
		Name:       "wakatimes",
		Columns:    WakatimesColumns,
		PrimaryKey: []*schema.Column{WakatimesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "wakatime_member_id",
				Unique:  false,
				Columns: []*schema.Column{WakatimesColumns[3]},
			},
			{
				Name:    "wakatime_key",
				Unique:  false,
				Columns: []*schema.Column{WakatimesColumns[4]},
			},
		},
	}
	// WakatimeCategoriesColumns holds the columns for the "wakatime_categories" table.
	WakatimeCategoriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "wakatime_id", Type: field.TypeUUID, Comment: "wakatime id"},
		{Name: "member_id", Type: field.TypeUUID, Comment: "会员id"},
		{Name: "name", Type: field.TypeString, Comment: "名称", Default: ""},
		{Name: "total_seconds", Type: field.TypeInt64, Comment: "总时长(秒", Default: 0},
	}
	// WakatimeCategoriesTable holds the schema information for the "wakatime_categories" table.
	WakatimeCategoriesTable = &schema.Table{
		Name:       "wakatime_categories",
		Comment:    "每日category统计表",
		Columns:    WakatimeCategoriesColumns,
		PrimaryKey: []*schema.Column{WakatimeCategoriesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "wakatimecategory_wakatime_id",
				Unique:  false,
				Columns: []*schema.Column{WakatimeCategoriesColumns[3]},
			},
			{
				Name:    "wakatimecategory_member_id_name",
				Unique:  false,
				Columns: []*schema.Column{WakatimeCategoriesColumns[4], WakatimeCategoriesColumns[5]},
			},
		},
	}
	// WakatimeDependenciesColumns holds the columns for the "wakatime_dependencies" table.
	WakatimeDependenciesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "wakatime_id", Type: field.TypeUUID, Comment: "wakatime id"},
		{Name: "member_id", Type: field.TypeUUID, Comment: "会员id"},
		{Name: "name", Type: field.TypeString, Comment: "名称", Default: ""},
		{Name: "total_seconds", Type: field.TypeInt64, Comment: "总时长(秒", Default: 0},
	}
	// WakatimeDependenciesTable holds the schema information for the "wakatime_dependencies" table.
	WakatimeDependenciesTable = &schema.Table{
		Name:       "wakatime_dependencies",
		Comment:    "每日dependency统计表",
		Columns:    WakatimeDependenciesColumns,
		PrimaryKey: []*schema.Column{WakatimeDependenciesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "wakatimedependency_wakatime_id",
				Unique:  false,
				Columns: []*schema.Column{WakatimeDependenciesColumns[3]},
			},
			{
				Name:    "wakatimedependency_member_id_name",
				Unique:  false,
				Columns: []*schema.Column{WakatimeDependenciesColumns[4], WakatimeDependenciesColumns[5]},
			},
		},
	}
	// WakatimeDurationsColumns holds the columns for the "wakatime_durations" table.
	WakatimeDurationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// WakatimeDurationsTable holds the schema information for the "wakatime_durations" table.
	WakatimeDurationsTable = &schema.Table{
		Name:       "wakatime_durations",
		Columns:    WakatimeDurationsColumns,
		PrimaryKey: []*schema.Column{WakatimeDurationsColumns[0]},
	}
	// WakatimeEditorsColumns holds the columns for the "wakatime_editors" table.
	WakatimeEditorsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// WakatimeEditorsTable holds the schema information for the "wakatime_editors" table.
	WakatimeEditorsTable = &schema.Table{
		Name:       "wakatime_editors",
		Columns:    WakatimeEditorsColumns,
		PrimaryKey: []*schema.Column{WakatimeEditorsColumns[0]},
	}
	// WakatimeEntitiesColumns holds the columns for the "wakatime_entities" table.
	WakatimeEntitiesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// WakatimeEntitiesTable holds the schema information for the "wakatime_entities" table.
	WakatimeEntitiesTable = &schema.Table{
		Name:       "wakatime_entities",
		Columns:    WakatimeEntitiesColumns,
		PrimaryKey: []*schema.Column{WakatimeEntitiesColumns[0]},
	}
	// WakatimeGrandTotalsColumns holds the columns for the "wakatime_grand_totals" table.
	WakatimeGrandTotalsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// WakatimeGrandTotalsTable holds the schema information for the "wakatime_grand_totals" table.
	WakatimeGrandTotalsTable = &schema.Table{
		Name:       "wakatime_grand_totals",
		Columns:    WakatimeGrandTotalsColumns,
		PrimaryKey: []*schema.Column{WakatimeGrandTotalsColumns[0]},
	}
	// WakatimeHeartBeatsColumns holds the columns for the "wakatime_heart_beats" table.
	WakatimeHeartBeatsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// WakatimeHeartBeatsTable holds the schema information for the "wakatime_heart_beats" table.
	WakatimeHeartBeatsTable = &schema.Table{
		Name:       "wakatime_heart_beats",
		Columns:    WakatimeHeartBeatsColumns,
		PrimaryKey: []*schema.Column{WakatimeHeartBeatsColumns[0]},
	}
	// WakatimeLanguagesColumns holds the columns for the "wakatime_languages" table.
	WakatimeLanguagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// WakatimeLanguagesTable holds the schema information for the "wakatime_languages" table.
	WakatimeLanguagesTable = &schema.Table{
		Name:       "wakatime_languages",
		Columns:    WakatimeLanguagesColumns,
		PrimaryKey: []*schema.Column{WakatimeLanguagesColumns[0]},
	}
	// WakatimeProjectsColumns holds the columns for the "wakatime_projects" table.
	WakatimeProjectsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// WakatimeProjectsTable holds the schema information for the "wakatime_projects" table.
	WakatimeProjectsTable = &schema.Table{
		Name:       "wakatime_projects",
		Columns:    WakatimeProjectsColumns,
		PrimaryKey: []*schema.Column{WakatimeProjectsColumns[0]},
	}
	// WakatimeProjectDurationsColumns holds the columns for the "wakatime_project_durations" table.
	WakatimeProjectDurationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// WakatimeProjectDurationsTable holds the schema information for the "wakatime_project_durations" table.
	WakatimeProjectDurationsTable = &schema.Table{
		Name:       "wakatime_project_durations",
		Columns:    WakatimeProjectDurationsColumns,
		PrimaryKey: []*schema.Column{WakatimeProjectDurationsColumns[0]},
	}
	// WakatimeProjectInfosColumns holds the columns for the "wakatime_project_infos" table.
	WakatimeProjectInfosColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// WakatimeProjectInfosTable holds the schema information for the "wakatime_project_infos" table.
	WakatimeProjectInfosTable = &schema.Table{
		Name:       "wakatime_project_infos",
		Columns:    WakatimeProjectInfosColumns,
		PrimaryKey: []*schema.Column{WakatimeProjectInfosColumns[0]},
	}
	// WakatimeSystemsColumns holds the columns for the "wakatime_systems" table.
	WakatimeSystemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// WakatimeSystemsTable holds the schema information for the "wakatime_systems" table.
	WakatimeSystemsTable = &schema.Table{
		Name:       "wakatime_systems",
		Columns:    WakatimeSystemsColumns,
		PrimaryKey: []*schema.Column{WakatimeSystemsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		MembersTable,
		MemberAuthorizeLogsTable,
		MemberRelatedRolesTable,
		MemberRolesTable,
		MemberRoleRelatedPermissionsTable,
		PermissionGroupsTable,
		PermissionRelatedRoutersTable,
		RoutersTable,
		SourceDataTable,
		WakatimesTable,
		WakatimeCategoriesTable,
		WakatimeDependenciesTable,
		WakatimeDurationsTable,
		WakatimeEditorsTable,
		WakatimeEntitiesTable,
		WakatimeGrandTotalsTable,
		WakatimeHeartBeatsTable,
		WakatimeLanguagesTable,
		WakatimeProjectsTable,
		WakatimeProjectDurationsTable,
		WakatimeProjectInfosTable,
		WakatimeSystemsTable,
	}
)

func init() {
	MembersTable.Annotation = &entsql.Annotation{}
	WakatimeCategoriesTable.Annotation = &entsql.Annotation{}
	WakatimeDependenciesTable.Annotation = &entsql.Annotation{}
}
